### PR TITLE
bug fix and add support import librarys

### PR DESCRIPTION
**Pull request by niceue**
1. deeping extend for settings
2. `data-files-js="jquery.js; "` should remove last space
3. `clearInterval(timer)` for performance
4. support libs param

**eg.**

```js
$('.editr').each(function() {
    new Editr({
		el: this,
		libs: [
			'/demo/demo.css',
			'/js/libs/jquery/1.11.3/jquery.min.js'
		]
	});
});
```

### CODE REVIEW

**Comment by Idered** [comment]
Thanks :+1:

**Comment by niceue** [comment]
This plugin is useful for me :+1:  , i do not want to show and edit third-party libraries like `jquery`, so i add support libs parameter.
I made an demonstrate：
http://validator.niceue.com/demo.html

**Comment by Idered** [comment]
You can always put "!" before file you want to load to hide  it from nav.  I hope you haven't break this functionality :)

I'm working on v3 totally rebuilded with some more  functions and cleaner code but it might take some time..

**Comment by niceue** [comment]
Yes, but only works for the same domain, because of ajax request.
And the script request is better than ajax and “eval”.
When i use `data-files-js="!http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js"` the request file is:
`http://validator.niceue.com/items/http://cdn.bootcss.com/jquery/1.11.3/jquery.min.js`

**Pull request merged**
